// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnjqgdttknlyarxijpsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuanFnZHR0a25seWFyeGlqcHN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjE2OTcsImV4cCI6MjA2MTQzNzY5N30.mjpTnyjvl7iRfJF-tC-srafrhWC4UDV4UtoFSfTd58c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});